version: "3.9"
services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                REACT_APP_SRYGOSPIZZA_BACKEND_URL: ${SRYGOSPIZZA_BACKEND_URL}
        image: srygospizza-frontend:latest
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            - backend
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: srygospizza-backend:latest
        restart: unless-stopped
        ports:
            - "8080:8080"
