spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:database
        username: sa
        password: ''
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: false
        hibernate:
            ddl-auto: create-drop
    profiles.active:
        - mockDishes
        - mockOrders
